# Generated by Django 6.0.5 on 2026-06-01 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_ambiente', '0001_initial'),
        ('modulo_curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciclo_academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cic_año', models.CharField(max_length=4)),
                ('cic_semestre', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Ciclo académico',
            },
        ),
        migrations.CreateModel(
            name='dia_semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_nombre', models.CharField(max_length=9)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Día de la semana',
            },
        ),
        migrations.CreateModel(
            name='escuela_ambiente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FK_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_ambiente.ambiente', verbose_name='Ambiente')),
                ('FK_ciclo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_horario.ciclo_academico', verbose_name='ciclo')),
                ('FK_escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_curso.escuela', verbose_name='Escuela')),
            ],
        ),
        migrations.CreateModel(
            name='grupo_horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=1)),
                ('capacidad', models.PositiveSmallIntegerField(default=15)),
                ('fk_ciclo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_horario.ciclo_academico')),
                ('fk_curso', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_curso.curso')),
            ],
            options={
                'verbose_name_plural': 'Grupo Horario',
            },
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_de_inicio', models.CharField(default='00:00', max_length=5, verbose_name='Hora de inicio')),
                ('hora_final', models.CharField(default='00:00', max_length=5)),
                ('motivo_cambio', models.CharField(blank=True, max_length=150, null=True)),
                ('ambiente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_ambiente.ambiente')),
                ('día', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_horario.dia_semana', verbose_name='Día')),
                ('fk_grupo_horario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_horario.grupo_horario', verbose_name='Curso')),
            ],
            options={
                'verbose_name_plural': 'Horario',
            },
        ),
    ]
