# Generated by Django 6.0.5 on 2026-06-01 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_edificio', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Edificio',
            },
        ),
        migrations.CreateModel(
            name='tipo_ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_ambiente', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipo de ambiente',
            },
        ),
        migrations.CreateModel(
            name='ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ambiente', models.CharField(max_length=30)),
                ('capacidad_ambiente', models.PositiveSmallIntegerField(default=15)),
                ('estado_ambiente', models.CharField(choices=[('D', 'Disponible'), ('O', 'Ocupado'), ('M', 'Mantenimiento')], max_length=1)),
                ('piso', models.PositiveSmallIntegerField(default=1)),
                ('FKedificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_ambiente.edificio', verbose_name='Edificio')),
                ('FKtipo_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_ambiente.tipo_ambiente', verbose_name='Tipo de Ambiente')),
            ],
            options={
                'verbose_name_plural': 'Ambiente',
            },
        ),
    ]
