# Generated by Django 6.0.5 on 2026-06-01 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_facultad', models.CharField(max_length=100)),
                ('responsable_facultad', models.CharField(default='Sin responsable', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Facultad',
            },
        ),
        migrations.CreateModel(
            name='tipo_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_curso', models.CharField(default='Curso presencial', max_length=100)),
                ('descripcion_curso', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipo de curso',
            },
        ),
        migrations.CreateModel(
            name='escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escuela', models.CharField(max_length=60)),
                ('director_escuela', models.CharField(default='Sin director', max_length=60)),
                ('fk_facultad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_curso.facultad')),
            ],
            options={
                'verbose_name_plural': 'Escuela',
            },
        ),
        migrations.CreateModel(
            name='plan_estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_nombre', models.CharField(default='plan 2024', max_length=60)),
                ('plan_descripcion', models.CharField(max_length=60)),
                ('plan_fechacreacion', models.DateField()),
                ('plan_estado', models.BooleanField(default=True)),
                ('fk_escuela', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_curso.escuela')),
            ],
            options={
                'verbose_name_plural': 'Plan de estudio',
            },
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=20, unique=True)),
                ('nombre_curso', models.CharField(max_length=100)),
                ('horas_totales', models.SmallIntegerField(default=1)),
                ('horas_practicas', models.SmallIntegerField(default=1)),
                ('horas_teoricas', models.SmallIntegerField(default=1)),
                ('ciclo_curso', models.SmallIntegerField(default=1)),
                ('amb', models.SmallIntegerField(default=1)),
                ('FKplan_estudio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_curso.plan_estudio')),
                ('FKtipocurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_curso.tipo_curso')),
            ],
            options={
                'verbose_name_plural': 'Curso',
            },
        ),
    ]
