# Generated by Django 6.0.5 on 2026-06-01 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_horario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='departamento_academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_nombre', models.CharField(max_length=50)),
                ('dep_director', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Departamento académico',
            },
        ),
        migrations.CreateModel(
            name='tipo_contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_nombre', models.CharField(max_length=50)),
                ('tp_descripcion', models.CharField(max_length=100)),
                ('tp_horas', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Tipo de contrato',
            },
        ),
        migrations.CreateModel(
            name='docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_nombres', models.CharField(max_length=200)),
                ('doc_especialidad', models.CharField(max_length=100)),
                ('doc_email', models.CharField(max_length=50)),
                ('doc_estado', models.CharField(max_length=10)),
                ('doc_telefono', models.CharField(max_length=9)),
                ('FKdepartamentoacademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_docente.departamento_academico')),
                ('FKtipocontrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_docente.tipo_contrato')),
            ],
            options={
                'verbose_name_plural': 'Docente',
            },
        ),
        migrations.CreateModel(
            name='disponibilidad_docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ddo_horainicio', models.TimeField()),
                ('ddo_horafin', models.TimeField()),
                ('FKdiasemana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_horario.dia_semana')),
                ('FKdocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_docente.docente')),
            ],
            options={
                'verbose_name_plural': 'Disponibilidad docente',
                'ordering': ['FKdocente'],
            },
        ),
        migrations.CreateModel(
            name='docente_grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FKdocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_docente.docente')),
                ('FKgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_horario.grupo_horario')),
            ],
            options={
                'verbose_name_plural': 'Docente grupo',
                'ordering': ['id'],
            },
        ),
    ]
